export const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SET_BANNERS: 'SET_BANNERS',
    SET_MOVIE_DETAIL: 'SET_MOVIE_DETAIL',
    SET_INFO_CINEMA:'SET_INFO_CINEMA',
    SET_LIST_INFO_CINEMA:'SET_LIST_INFO_CINEMA',
}