export const SET_MOVIES_LIST = 'SET_MOVIES_LIST'
export const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU'
export const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU'
export const SET_BANNER_LIST = 'SET_BANNER_LIST'
