export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNUP = 'USER_SIGNUP'
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG'
export const CAP_NHAT_THONG_TIN_NGUOI_DUNG = 'CAP_NHAT_THONG_TIN_NGUOI_DUNG'

